# Generated by Django 3.1.1 on 2020-10-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ClubName', models.CharField(max_length=50)),
                ('RepresentativeName', models.CharField(max_length=50)),
                ('Contact', models.CharField(max_length=12)),
                ('req_date_from', models.DateField()),
                ('req_date_to', models.DateField()),
                ('req_type', models.CharField(max_length=50)),
                ('req_purpose', models.TextField(max_length=50)),
                ('formtime', models.DateTimeField()),
            ],
        ),
    ]
