# Generated by Django 3.1.1 on 2020-10-28 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='email',
            field=models.CharField(default='abc@xyz.com', max_length=50),
        ),
    ]
