# Generated by Django 3.1.1 on 2020-11-06 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0002_form_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='formtime',
        ),
        migrations.AddField(
            model_name='form',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='form',
            name='ClubName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='form',
            name='Contact',
            field=models.CharField(default=None, max_length=12),
        ),
        migrations.AlterField(
            model_name='form',
            name='RepresentativeName',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='form',
            name='email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='form',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='form',
            name='req_date_from',
            field=models.DateField(default='timezone.now'),
        ),
        migrations.AlterField(
            model_name='form',
            name='req_date_to',
            field=models.DateField(default='timezone.now'),
        ),
        migrations.AlterField(
            model_name='form',
            name='req_purpose',
            field=models.TextField(blank=True, default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='form',
            name='req_type',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
