# Generated by Django 3.1.1 on 2020-11-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0004_auto_20201106_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='alloted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='form',
            name='req_date_from',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='form',
            name='req_date_to',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='form',
            name='req_purpose',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='form',
            name='req_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
