# Generated by Django 3.1.1 on 2020-11-07 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0005_auto_20201106_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='Management_Comments',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
