# Generated by Django 3.1.1 on 2020-11-08 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dash', '0009_auto_20201108_0030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Allot',
        ),
    ]
